apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchen-front
  labels:
    app: kitchen
    role: front
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: kitchen
      role: front
  template:
    metadata:
      labels:
        app: kitchen
        role: front
    spec:
      containers:
      - name: front
        image: nicholasescalona/proj2ui:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: '0.25'
            memory: 128Mi
