apiVersion: v1
kind: Service
metadata:
  name: simpleorder-mvc
  labels:
    app: simpleorder
    role: mvc
spec:
  type: LoadBalancer
  selector:
    app: simpleorder
    role: mvc
  ports:
    - port: 80
